version: '3.8'
services:
  api-service:
    build:
      context: .
      dockerfile: apps/api-service/Dockerfile
    ports:
      - 3001:3000

  user-service:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
    ports:
      - 3002:3000