version: '3.8'
services:
  api-service:
    container_name: api-service
#    network_mode: bridge
    build:
      context: .
      dockerfile: apps/api-service/Dockerfile
    ports:
      - 3001:3000

  user-service:
    container_name: user-service
#    network_mode: bridge
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
    ports:
      - 3002:3000

  rabbit-mq:
    container_name: rabbit-mq
#    network_mode: bridge
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

#networks:
#  microservices-demo-network:
#    external: true