version: '3.8'
services:
  api-service:
    container_name: api-service
    network_mode: bridge
    build:
      context: .
      dockerfile: apps/api-service/Dockerfile
    ports:
      - 3001:3000

  user-service:
    container_name: user-service
    network_mode: bridge
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
    ports:
      - 3002:3000

networks:
  microservices-demo-network:
    external: true